language: generic

rvm: 1.9.3

sudo: false

env:
  global:
  - PATH="/opt/chef/bin:$PATH"
  matrix:
  - COOKBOOK_PATH="ci_environment"
  - COOKBOOK_PATH="worker_host" FC_ARGS="--exclude ./worker-host/opsmatic-cookbook" 

addons:
  apt:
    sources:
    - chef-stable-precise
    packages:
    - chefdk

script:
- foodcritic $FC_ARGS --tags $(cat .foodcritic-tags) $COOKBOOK_PATH
