language: generic

sudo: false

env:
  global:
  - PATH="/opt/chefdk/bin:/opt/chef/bin:/opt/chef/embedded/bin:/opt/chefdk/embedded/bin:$PATH"
  matrix:
  - COOKBOOK_PATH="cookbooks"
  - COOKBOOK_PATH="community-cookbooks"

addons:
  apt:
    sources:
    - chef-stable-precise
    packages:
    - chefdk

script:
- which rubocop
- find /opt/chef* -name rubocop | while read -r line; do echo "---> ${line} --verbose-version"; "${line}" --verbose-version; done
- ./runtests
