language: generic

sudo: false

env:
  global:
  - PATH="/opt/chef/bin:$PATH"
  matrix:
  - COOKBOOK_PATH="cookbooks"
  - COOKBOOK_PATH="community-cookbooks"

addons:
  apt:
    sources:
    - chef-stable-precise
    packages:
    - chefdk

script: ./run-foodcritic $COOKBOOK_PATH
