language: generic

sudo: false

env:
  global:
  - PATH="/opt/chefdk/bin:/opt/chef/bin:$PATH"
  matrix:
  - COOKBOOK_PATH="cookbooks"
  - COOKBOOK_PATH="community-cookbooks"

addons:
  apt:
    sources:
    - chef-stable-precise
    packages:
    - chefdk

script:
- unset GEM_PATH
- "if [[ -f $COOKBOOK_PATH/.rubocop.yml ]] ; then (cd $COOKBOOK_PATH && rubocop) ; fi"
- "./run-foodcritic $COOKBOOK_PATH"
